apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat-deploy
  labels:
    k8s-app: heartbeat
    task: log-monitoring
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 150
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heartbeat
      task: log-monitoring
  template:
    metadata:
      name: heartbeat-pod-template
      labels:
        k8s-app: heartbeat
        task: log-monitoring
    spec:
      containers:
      - image: 131.131.131.201:5000/beats/heartbeat:6.3.1
        imagePullPolicy: IfNotPresent
        name: heartbeat-container
        volumeMounts:
        - mountPath: /usr/share/heartbeat/heartbeat.yml
          subPath: heartbeat.yml
          name: config
      volumes:
      - name: config
        configMap:
          name: heartbeat
          items:
          - key: heartbeat.yml
            path: heartbeat.yml
