apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: browser1
    type: front-end
  name: browser1-deploy
  namespace: hotscan
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: browser1
      type: front-end
  template:
    metadata:
      labels:
        k8s-app: browser1
        type: front-end
      name: browser1-pod
      namespace: hotscan
    spec:
      containers:
      - image: 131.131.131.201:5000/hotscan/browser:v8.3.1
        name: browser1-deploy
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /apache-tomcat-7.0.88/bin/logs/
          name: exchange
      - image: 131.131.131.201:5000/beats/filebeat:6.3.1
        imagePullPolicy: IfNotPresent
        name: browser1-filebeat-container
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: config
        - mountPath: /usr/share/filebeat/logs/
          name: exchange
      volumes:
      - name: exchange
        emptyDir: {}
      - name: config
        configMap:
          name: filebeat
          items:
          - key: filebeat-browser.yml
            path: filebeat.yml
      nodeName: node1

---

apiVersion: v1
kind: Service
metadata:
  name: browser1-service
  labels:
    k8s-app: browser1
    type: front-end
  namespace: hotscan
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
  selector:
    k8s-app: browser1
    type: front-end

