apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: browser
    type: front-end
  name: browser-deploy
  namespace: hotscan
  annotations:
    kubernetes.io/change-cause: "Hotscan Active-Active release:v9.0.0"
spec:
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      k8s-app: browser
      type: front-end
  template:
    metadata:
      labels:
        k8s-app: browser
        type: front-end
      name: browser-pod
      namespace: hotscan
    spec:
      containers:
      - image: 131.131.131.201:5000/hotscan/browser:v8.5.0
        name: browser-deploy
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: HotScan
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: HotScan
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /apache-tomcat-7.0.88/bin/logs/
          name: exchange
      - image: 131.131.131.201:5000/beats/filebeat:6.3.1
        imagePullPolicy: IfNotPresent
        name: browser-filebeat-container
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: config
        - mountPath: /usr/share/filebeat/logs/
          name: exchange
      volumes:
      - name: exchange
        emptyDir: {}
      - name: config
        configMap:
          name: browser
          items:
          - key: filebeat-browser
            path: filebeat.yml

---

apiVersion: v1
kind: Service
metadata:
  name: browser-service
  labels:
    k8s-app: browser
    type: front-end
  namespace: hotscan
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 30080
  selector:
    k8s-app: browser
    type: front-end

