apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-deploy
  labels:
    k8s-app: filebeat
    task: log-monitoring
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 150
  replicas: 1
  selector:
    matchLabels:
      k8s-app: filebeat
      task: log-monitoring
  template:
    metadata:
      name: filebeat-pod-template
      labels:
        k8s-app: filebeat
        task: log-monitoring
    spec:
      containers:
      - image: 131.131.131.201:5000/beats/filebeat:6.3.1
        imagePullPolicy: IfNotPresent
        name: filebeat-container
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          name: config
      volumes:
      - name: config
        configMap:
          name: filebeat
          items:
          - key: filebeat.yml
            path: filebeat.yml
