apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  labels:
    k8s-app: kibana
    task: log-monitoring
spec:
  ports:
  - name: kibana-svc-port
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 31001
  selector:
    k8s-app: kibana
    task: log-monitoring
  type: NodePort

