apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deploy
  labels:
    k8s-app: elasticsearch
    task: log-monitoring
  namespace: elkstack
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 150
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      task: log-monitoring
  template:
    metadata:
      name: elasticsearch-pod-template
      labels:
        k8s-app: elasticsearch
        task: log-monitoring
      namespace: elkstack
    spec:
      containers:
      - image: 131.131.131.201:5000/elasticsearch/elasticsearch:6.3.1
        imagePullPolicy: IfNotPresent
        name: elasticsearch-container
        ports:
        - containerPort: 9200
          hostPort: 9200
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: persistent
      volumes:
      - name: persistent
        hostPath:
            path: /home/ansible/elasticsearch-do-not-delete/
      nodeSelector:
        vmmax: ok
---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  labels:
    k8s-app: elasticsearch
    task: log-monitoring
  namespace: elkstack
spec:
  ports:
  - name: elasticsearch-svc-port
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    k8s-app: elasticsearch
    task: log-monitoring
  type: ClusterIP

