heartbeat.monitors:
- type: tcp
  schedule: '@every 20s' 
  hosts: ["131.131.131.201"]
  ports: [1521, 30001]
  mode: any 

output.elasticsearch:
  hosts: ["elasticsearch-svc.default.svc.cluster.local:9200"]

setup.kibana:
  host: "kibana-svc.default.svc.cluster.local:5601"
