
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: elkstack
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.url: "http://elasticsearch-data-svc.elkstack.svc.cluster.local:9200"
    xpack.monitoring.ui.container.elasticsearch.enabled: false
