apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash-daemon
  labels:
    k8s-app: logstash
    task: log-monitoring
  namespace: elkstack
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      k8s-app: logstash
      task: log-monitoring
  template:
    metadata:
      name: logstash-pod-template
      labels:
        k8s-app: logstash
        task: log-monitoring
      namespace: elkstack
    spec:
      containers:
      - image: 131.131.131.201:5000/logstash/logstash:6.3.1
        imagePullPolicy: IfNotPresent
        name: logstash-container
        ports:
        - containerPort: 5044
          hostPort: 5044
          protocol: TCP
        - containerPort: 5043
          hostPort: 5043
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          name: config
        - mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
          name: pipeline-config
        - mountPath: /usr/share/logstash/pipeline
          name: pipelines
      volumes:
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: pipeline-config
        configMap:
          name: logstash
          items:
          - key: pipelines.yml
            path: pipelines.yml
      - name: pipelines
        configMap:
          name: logstash
          items:
          - key: browser.conf
            path: browser.conf
          - key: controller.conf
            path: controller.conf
