apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deploy
  labels:
    k8s-app: logstash
    task: log-monitoring
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 150
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logstash
      task: log-monitoring
  template:
    metadata:
      name: logstash-pod-template
      labels:
        k8s-app: logstash
        task: log-monitoring
    spec:
      containers:
      - image: 131.131.131.201:5000/logstash/logstash:6.3.1
        imagePullPolicy: IfNotPresent
        name: logstash-container
        ports:
        - containerPort: 5044
          hostPort: 5044
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          name: config
        - mountPath: /usr/share/logstash/pipeline
          name: pipeline
      volumes:
      - name: config
        configMap:
          name: logstash
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: pipeline
        configMap:
          name: logstash
          items:
          - key: logstash.conf
            path: logstash.conf
