apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: elkstack
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.url: "elasticsearch-data-svc.elkstack.svc.cluster.local:9200"

  pipelines.yml: |
    - pipeline.id: browser
      path.config: "/usr/share/logstash/pipeline/browser.conf"
    - pipeline.id: controller
      path.config: "/usr/share/logstash/pipeline/controller.conf"

  browser.conf: |
    input {
      beats {
        port => 5043
        tags => "browser"
      }
    }

    filter {
        grok {
            match => { "message" => "(?<date>[0-9]*)\s*(?<month>[A-Za-z]{3})\s*(?<year>[0-9]{4})\s*(?<time>(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?));\s*;(?<error_type>.*);(?<class>.*);(?<message>.*)"
            }
            remove_field => ["message"]
        }
    }

    output {
        elasticsearch {
            hosts => "elasticsearch-data-svc.elkstack.svc.cluster.local:9200"
            index => "browser-logs-%{+YYYY.MM.dd}"
        }
    }

  controller.conf: |
    input {
      beats {
        port => 5044
        tags => "controller"
      }
    }

    filter {
          grok {
              match => { "message" => "^(?<day>[0-9]{6})\s+(?<time>(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?))\s+(?<process_id>[0-9]*)\s+(?<process>[a-zA-Z0-9]*):\s+(?<log>.*)"
              }
              remove_field => ["message"]
          }

          grok {
              match => { "message" => "^(?<day>[0-9]{6})\s+(?<time>(?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?))\s+(?<process>[a-zA-Z0-9]*):\s+(?<log>.*)"
              }
              remove_field => ["message"]
          }
    }

    output {
        elasticsearch {
            hosts => "elasticsearch-data-svc.elkstack.svc.cluster.local:9200"
            index => "controller-logs-%{+YYYY.MM.dd}"
        }
    }
