apiVersion: v1
kind: ConfigMap
metadata:
  name: controller
  namespace: hotscan
data: 
  filebeat-controller: |
    filebeat:
      inputs:
      - type: log
        enabled: true
        paths:
        - /usr/share/filebeat/logs/*.log
        fields:
          node: ${NODE_NAME}
        fields_under_root: true

    output:
      logstash:
        hosts: "${NODE_IP}:5044"
  ocs: |
    #HotScan Online Controller Settings - OCS.INI
    ##############################[ HotScanSetting ]##############################
    [General]
    HOTSCAN_DIRECTORY = /home/hotscan/
    HS_DICTIONARY_SORT_WORKSPACE = /home/hotscan/temp/
    OCS_BASE_DIRECTORY = /home/hotscan/TODAY/
    OCS_DAY_OLD_DIRECTORY = /home/hotscan/YESTERDAY/

    ##############################[ HotScan IPCQConn ]##############################
    [HotScanQIPC]
    IPC_MQ_HOST = localhost
    IPC_MQ_PORT_NUMBER = 7676
    #IPC_MQ_CHANNEL = ChannelName

    IPC_MQ_PERSISTENT = OFF
    IPC_MQ_BATCHCOUNT = 0
    MQ_BATCH_RECOVERY_CNT = 3
    IPC_MQ_CONNECTION_FLOW_LIMIT = 50
    IPC_MQ_CONNECTION_FLOW_BATCH_COUNT = 50
    AL_QIPC_MODE = SHARED

    [IPCQueues]
    REALTIME_IPC_QUEUE = HOTSCANQ.RealTimeQ
    AL_STAGE_IPC_QUEUE = HOTSCANQ.AlStageQ

    REQUEST_QCOUNT = 1
    REQUEST_Q1 = HOTSCANQ.RequestQ1

    RESPONSE_QCOUNT = 1
    RESPONSE_Q1 = HOTSCANQ.ResponseQ1

    ##############################[ AlgorithmSetting ]##############################
    [Algorithm]
    HOSTNAME_I = localhost
    NUMBER_OF_ALS = 1
    NUMBER_HOST_ALS = 1
    NUMBER_OF_BIG_ALS = 0
    AL_HOST1 = localhost
    PROCESS_TIMEOUT = 7200
    SCAN_TIME_THRESHOLD = 0

    [ALGORITHM CONDITIONAL SCAN SETTINGS]
    APPLY_TOKEN_AS_PER_MINWORDSIZE = OFF
    NUM_PCT_OF_WORD = 0
    CNS_MATCH_DISTANT_NUM_OF_CHAR = 1
    CNS_REPLACE_BY_SPACE_CHARS = .,'-
    NEWLINE_DEL_NONSWF = ON
    HKMA = 0
    LOAD_COND_SCAN_SETTINGS = ON
    [NAME FIELD SCANNING]
    NAME_FIELD_CALC = OFF

    [AlgorithmBoost]
    BOOST_PCT_OF_WORD = OFF
    BOOST_COMMON_WRD_SDN = OFF
    BOOST_SPLCHR_SCANNING = OFF
    BOOST_INITIAL_SCANNING = OFF
    BOOST_STOP_CHAR_IN_SEQUENCE = 0

    [SingleWord]
    SINGLE_WORD_NAME_ADJUST_EXCL_SDNLEN = 0
    SINGLE_WORD_NAME_ADJUST = ON
    LOAD_GOODGUY_CONFIGURED = OFF

    [Performance]
    SDN_MATCH_FILTER = OFF
    UNIQUE_TRN_WORDS = OFF
    NUM_PCT_TAG_SDN_SUPRESS = 0
    LEN_PCT_TAG_SDN_SUPRESS = 0

    [MsgPriority]
    MESSAGE_PRIORITY = OFF

    [EUVO_SCANNIG]
    EUVO_SCANNING = OFF

    [ZERO LOAD ALGORITHM]
    AL_ZERO_LOAD = OFF
    #AL_ZERO_LOAD_NO_DEVRS = OFF
    #AL_ZERO_LOAD_NUM = 1
    #AL_ZERO_LOAD_NO_DEVRS_NUM =  1
    
    ##############################[ TCPIP/HostConfig ]##############################
    [Bessrcv]
    BESSRCV_CMD_SERVICE = bessrcv
    OCP_S_SERVICE = BESSDOCKER
    BESSRCV_BESS_FORMAT = 0
    SLEEP_TIMER = 30

    [Besssnd]
    BESSSND_CMD_SERVICE = besssnd
    OCP_R_SERVICE = ocp_rDOCKER
    CONNECT_RETRY_TIMER = 1
    CONNECT_RETRY_MSG_TIMER = 30
    NUMBER_OF_HOSTS = 2
    FAIL_REASON_CODE = OFF

    [TCPIPHostConfiguration]
    HOST1 = localhost
    HOST1_OCP_R_COUNT = 1
    RESCAN_DUP_TXN_HOST1 = OFF
    DELIMIT_CHAR_HOST1 = -
    #TCPIP_HOST1_SOURCE_ID = TCP_IP1
    #TCPIP_HOST1_DEST_ID = TCP_IP1

    #MQ Host Configuration
    HOST2 = 131.131.131.201
    HOST2_OCP_R_COUNT = 1
    #RESCAN_DUP_TXN_HOST2 = OFF
    HOST2_TYPE_MQ = ON
    DELIMIT_CHAR_HOST2 = -

    #Lookup Host Configuration
    #HOST3 = <LOOKUP_host>
    #HOST3_OCP_R_COUNT = 1
    #RESCAN_DUP_TXN_HOST3 = OFF
    #DELIMIT_CHAR_HOST3 = -


    [SAI-Plugin]
    SAI_MSGPAIR = OFF
    HOSTn_TYPE = SAI



    [HostMessage]
    CHECK_RESUBMISSION_PAYMENT = OFF
    RBS_HOST_RESPONSE_CHECK = OFF
    AUTO_CRIT = OFF

    [Acknowledgement]
    ACK_TIMER = 600
    MAX_NO_ACK = 10
    HOST_ACK_SEND = ON
    HOST_ACK_RECV = ON
    EXT_HDR = ON

    ##############################[ Message Recovery ]##############################
    [HandleMsgLoss]
    CONF_RECOVERY = OFF
    AUTO_RECOVERY = OFF
    RECOVERY_RESCAN = OFF
    RECOVERY_RESEND = OFF
    TRANSACTION_MONITOR_TIMER = 60
    NUMBER_OF_RECOVERY_ATTEMPT = 3
    TRANSACTION_REVIEW_TIME = 480
    TRANSACTION_IDLE_TIME = 240
    AUTO_SHUTDOWN = OFF
    TRN_RECOVERY_ATTEMPT = 3

    ##############################[ Core Process Cfg ]##############################
    [Autocntl]
    AUTOCNTL_CMD_SERVICE = autocntl
    AUTOCNTL_TCP_SERVICE = autotcpDOCKER
    ALGORITHM_HOST_VALIDATION = ON
    KEEPALIVE_TIMEOUT = 20 
    SORT_TIMEOUT = 180

    [Dbcntl]
    DBCNTL_CMD_SERVICE = dbcntl
    DBCNTL_TCP_SERVICE = dbcntltcpDOCKER
    REALTIME_POLL_INTERVAL = 5
    #HITRATEDATA = SCH-23

    [Dbm]
    DBM_CMD_SERVICE = dbm
    KEEPALIVE_CMD_SERVICE = keepalive

    [Logger]
    LOGGER_CMD_SERVICE = logger
    LOGGER_IPC_QUEUE = HOTSCANQ.LoggerQ
    LOGGER_IPC_MQ_PERSISTENT = OFF

    [Mmicntl]
    MMICNTL_CMD_SERVICE = mmicntl
    MMICNTL_TCP_SERVICE = mmitcpDOCKER

    [Startall]
    STARTALL_CMD_SERVICE = startall
    MAX_DB_CONN_RETRY = 1440
    DB_CONN_RETRY_INTERVAL = 60

    ##############################[ EOD/POD/Reports  ]##############################
    [EodPod]
    EOD_WAIT = 60
    MOVE_TXN_TO_HISTORY = ON
    MOVE_PARTITION_DURING_EOD_POD = ON
    PURGEEOD_CMD_SERVICE = purgeeod
    PURGEEOD_RECOVERY = OFF
    PURGE_EOD = OFF

    [Reports]
    REPORT_DIRECTORY_NAME = /home/hotscan/spool/
    REPORTS_INITIALIZATION_FILE_NAME = REPORTS.INI
    NUMBER_OF_STAT_DAYS_TO_DISPLAY = 30
    ACCESS_ALL_STREAMS = ALL
    FAILED_TRANS_REPORT = 0

    [RunTimeReport]
    RT_REPORT_COUNT = 0
    REPORT_IPC_QUEUE = HOTSCANQ.RTReportQ
    REPORT_IPC_MQ_PERSISTENT = OFF
    RT_REPORT_BATCHFLUSH_REC = 1

    ##############################[ Logs - Debugging ]##############################
    [Oracle]
    ORACLE_LOG = OFF

    [HotScanDebugging]
    D_AUTOCNTL_PATH = autocntl.log
    D_AUTOCNTL_LEVEL = 2
    D_BESSRCV_PATH = bessrcv.log
    D_BESSRCV_LEVEL = 2
    D_BESSSND_PATH = besssnd.log
    D_BESSSND_LEVEL = 2
    D_DBM_PATH = dbm.log
    D_DBM_LEVEL = 2
    D_HSSTART_PATH = hsstart.log
    D_HSSTART_LEVEL = 2
    D_HSSTOP_PATH = hsstop.log
    D_HSSTOP_LEVEL = 2
    D_LOGGER_PATH = logger.log
    D_LOGGER_LEVEL = 2
    D_MMICNTL_PATH = mmicntl.log
    D_MMICNTL_LEVEL = 2
    D_PRINTSPL_PATH = printspl.log
    D_PRINTSPL_LEVEL = 2
    D_STARTALL_PATH = startall.log
    D_STARTALL_LEVEL = 2
    D_DBCNTL_PATH = dbcntl.log
    D_DBCNTL_LEVEL = 2
    D_PURGEEOD_LEVEL = 2
    D_ORACLE_PATH = oracledb.log
    D_ORACLE_LEVEL = 2
    D_RTREPORT_PATH = rtreport
    D_RTREPORT_LEVEL = 2

    ##############################[ Lookup Settings  ]##############################
    #Include parameters from LOOKUP.OCS.SMP

    ##############################[ MQInterface Cfg  ]##############################
    #Include parameters from MQ.OCS.SMP
    MQ_LINK = ON

    ##############################[ FileInterfaceCfg ]##############################
    #Include parameters from FI.OCS.SMP
    #HotScan v8 - MQ Host Support

    [MQInterface - Common parameters]
    MQ_LINK = ON
    MQ_PRIORITY_GETMSG_TIMER = 3
    CONNECTION_RETRY_INTERVAL = 5
    MQHOST_ACCESS_MODE = SHARED
    NUMBER_OF_MQHOSTS = 1
    NO_OF_HOTGET_INSTANCES = 1
    NO_OF_HOTPUT_INSTANCES = 1

    #Duplicate String Settings
    RESCAN_DUP_TXN_MQHOST = OFF
    DELIMIT_CHAR_MQHOST = -

    [Hotget - MQHost1 Settings]
    MQ_HOST1 = DOCKER
    MQ_CHANNEL1 = DOCKER_CHANNEL
    MQ_CONN1 = 131.131.131.201(30001)
    MQ_RCV_Q1 = HOTSCANINQ_30001
    SKIP_INTERVAL1 = 5
    #MQ_HOST_PRIORITY1 = 1
    #MQ_HOST1_SOURCE_ID = MQHOST1
    #MQ_HOST1_DEST_ID = MQHOST1
    #MQ_BATCH_SIZE1 = 20
    #MQ_BATCH_INTERVAL1 = 1000
    #MQ_BACKOUTQ1 = HotScanBackQ_1

    [Hotput - MQHost1 Settings]
    MQ_AUTORSP_Q1 = HOTSCANOUTQ1_30001
    MQ_MANRSP_Q1 = HOTSCANOUTQ2_30001
    MQ_REPLYTOQ1 = HOTSCANRPLYQ_30001
    MQ_BACKOUTQ1 = MQ_BACKOUTQ1_30001


    [Debugging]
    D_HOTGET_LEVEL = 3
    D_HOTPUT_LEVEL = 3

    [SSL SUPPORT]
    HOST2_TYPE = MQ
